// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tradesuggest.proto

package tradesuggest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TradeSuggestRequest struct {
	Resolution           int32    `protobuf:"varint,1,opt,name=resolution,proto3" json:"resolution,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeSuggestRequest) Reset()         { *m = TradeSuggestRequest{} }
func (m *TradeSuggestRequest) String() string { return proto.CompactTextString(m) }
func (*TradeSuggestRequest) ProtoMessage()    {}
func (*TradeSuggestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tradesuggest_bf01941c2c4594b5, []int{0}
}
func (m *TradeSuggestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeSuggestRequest.Unmarshal(m, b)
}
func (m *TradeSuggestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeSuggestRequest.Marshal(b, m, deterministic)
}
func (dst *TradeSuggestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeSuggestRequest.Merge(dst, src)
}
func (m *TradeSuggestRequest) XXX_Size() int {
	return xxx_messageInfo_TradeSuggestRequest.Size(m)
}
func (m *TradeSuggestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeSuggestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TradeSuggestRequest proto.InternalMessageInfo

func (m *TradeSuggestRequest) GetResolution() int32 {
	if m != nil {
		return m.Resolution
	}
	return 0
}

type Suggestion struct {
	Stockname            string   `protobuf:"bytes,1,opt,name=stockname,proto3" json:"stockname,omitempty"`
	Rating               int32    `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Direction            int32    `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Suggestion) Reset()         { *m = Suggestion{} }
func (m *Suggestion) String() string { return proto.CompactTextString(m) }
func (*Suggestion) ProtoMessage()    {}
func (*Suggestion) Descriptor() ([]byte, []int) {
	return fileDescriptor_tradesuggest_bf01941c2c4594b5, []int{1}
}
func (m *Suggestion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Suggestion.Unmarshal(m, b)
}
func (m *Suggestion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Suggestion.Marshal(b, m, deterministic)
}
func (dst *Suggestion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Suggestion.Merge(dst, src)
}
func (m *Suggestion) XXX_Size() int {
	return xxx_messageInfo_Suggestion.Size(m)
}
func (m *Suggestion) XXX_DiscardUnknown() {
	xxx_messageInfo_Suggestion.DiscardUnknown(m)
}

var xxx_messageInfo_Suggestion proto.InternalMessageInfo

func (m *Suggestion) GetStockname() string {
	if m != nil {
		return m.Stockname
	}
	return ""
}

func (m *Suggestion) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Suggestion) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type TradeSuggestResponse struct {
	Suggestions          []*Suggestion `protobuf:"bytes,1,rep,name=Suggestions,proto3" json:"Suggestions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TradeSuggestResponse) Reset()         { *m = TradeSuggestResponse{} }
func (m *TradeSuggestResponse) String() string { return proto.CompactTextString(m) }
func (*TradeSuggestResponse) ProtoMessage()    {}
func (*TradeSuggestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tradesuggest_bf01941c2c4594b5, []int{2}
}
func (m *TradeSuggestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeSuggestResponse.Unmarshal(m, b)
}
func (m *TradeSuggestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeSuggestResponse.Marshal(b, m, deterministic)
}
func (dst *TradeSuggestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeSuggestResponse.Merge(dst, src)
}
func (m *TradeSuggestResponse) XXX_Size() int {
	return xxx_messageInfo_TradeSuggestResponse.Size(m)
}
func (m *TradeSuggestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeSuggestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TradeSuggestResponse proto.InternalMessageInfo

func (m *TradeSuggestResponse) GetSuggestions() []*Suggestion {
	if m != nil {
		return m.Suggestions
	}
	return nil
}

func init() {
	proto.RegisterType((*TradeSuggestRequest)(nil), "TradeSuggestRequest")
	proto.RegisterType((*Suggestion)(nil), "Suggestion")
	proto.RegisterType((*TradeSuggestResponse)(nil), "TradeSuggestResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TradeSuggestServiceClient is the client API for TradeSuggestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TradeSuggestServiceClient interface {
	GetSuggestions(ctx context.Context, in *TradeSuggestRequest, opts ...grpc.CallOption) (*TradeSuggestResponse, error)
}

type tradeSuggestServiceClient struct {
	cc *grpc.ClientConn
}

func NewTradeSuggestServiceClient(cc *grpc.ClientConn) TradeSuggestServiceClient {
	return &tradeSuggestServiceClient{cc}
}

func (c *tradeSuggestServiceClient) GetSuggestions(ctx context.Context, in *TradeSuggestRequest, opts ...grpc.CallOption) (*TradeSuggestResponse, error) {
	out := new(TradeSuggestResponse)
	err := c.cc.Invoke(ctx, "/TradeSuggestService/GetSuggestions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeSuggestServiceServer is the server API for TradeSuggestService service.
type TradeSuggestServiceServer interface {
	GetSuggestions(context.Context, *TradeSuggestRequest) (*TradeSuggestResponse, error)
}

func RegisterTradeSuggestServiceServer(s *grpc.Server, srv TradeSuggestServiceServer) {
	s.RegisterService(&_TradeSuggestService_serviceDesc, srv)
}

func _TradeSuggestService_GetSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeSuggestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeSuggestServiceServer).GetSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TradeSuggestService/GetSuggestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeSuggestServiceServer).GetSuggestions(ctx, req.(*TradeSuggestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TradeSuggestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TradeSuggestService",
	HandlerType: (*TradeSuggestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuggestions",
			Handler:    _TradeSuggestService_GetSuggestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tradesuggest.proto",
}

func init() { proto.RegisterFile("tradesuggest.proto", fileDescriptor_tradesuggest_bf01941c2c4594b5) }

var fileDescriptor_tradesuggest_bf01941c2c4594b5 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x29, 0x4a, 0x4c,
	0x49, 0x2d, 0x2e, 0x4d, 0x4f, 0x4f, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32,
	0xe5, 0x12, 0x0e, 0x01, 0x89, 0x06, 0x43, 0x44, 0x83, 0x52, 0x0b, 0x4b, 0x81, 0x94, 0x90, 0x1c,
	0x17, 0x57, 0x51, 0x6a, 0x71, 0x7e, 0x4e, 0x69, 0x49, 0x66, 0x7e, 0x9e, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x6b, 0x10, 0x92, 0x88, 0x52, 0x02, 0x17, 0x17, 0x54, 0x07, 0x90, 0x27, 0x24, 0xc3, 0xc5,
	0x59, 0x5c, 0x92, 0x9f, 0x9c, 0x9d, 0x97, 0x98, 0x9b, 0x0a, 0x56, 0xcc, 0x19, 0x84, 0x10, 0x10,
	0x12, 0xe3, 0x62, 0x2b, 0x4a, 0x2c, 0xc9, 0xcc, 0x4b, 0x97, 0x60, 0x02, 0x9b, 0x03, 0xe5, 0x81,
	0x74, 0xa5, 0x64, 0x16, 0xa5, 0x26, 0x83, 0xad, 0x60, 0x06, 0x4b, 0x21, 0x04, 0x94, 0x5c, 0xb9,
	0x44, 0x50, 0x1d, 0x56, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0xa4, 0xcb, 0xc5, 0x8d, 0xb0, 0xb9,
	0x18, 0x68, 0x1b, 0xb3, 0x06, 0xb7, 0x11, 0xb7, 0x1e, 0x42, 0x2c, 0x08, 0x59, 0xde, 0x28, 0x0c,
	0xd5, 0x7f, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xf6, 0x5c, 0x7c, 0xee, 0xa9, 0x25,
	0x48, 0x0a, 0x85, 0x44, 0xf4, 0xb0, 0x84, 0x83, 0x94, 0xa8, 0x1e, 0x36, 0x47, 0x28, 0x31, 0x24,
	0xb1, 0x81, 0x83, 0xcf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x68, 0x1d, 0xe9, 0xf4, 0x54, 0x01,
	0x00, 0x00,
}
